### ISSUE TITLE
Roadmap v1.0

### ISSUE THREAD

**Issue by 7leodev** [7leodev/SkyDot#1]
## Lang:

- [ ] GDScript Full Source Code.
- [ ] C# Full Source Code.
- [ ] Godot Shader Lang Full Source Code.
---------------------------------------------------------------------

## Rendering:

- [ ] GLES3 Support.
- [ ] GLES2 Support.
- [ ] LDR/HDR Support.
- [ ] Fix Color Banding.

## Sky
**DeepSpace:**

- [ ] Background Panorama.
- [ ] Realistic Stars Field Panorama.

**NearSpace:**

- [ ] SunDisk.
- [ ] Realistic Moon and Moon Phases.

**Atmosphere:**

- [ ] ATI Paper Based Atmospheric Scattering.
- [ ] Moon Scattering.
- [ ] Semi Artistic Control.

**Clouds:**

- [ ] Dynamic Clouds.
---------------------------------------------------------------------
## Environment:

**Fog:**

- [ ] Environment Fog Control.
- [ ] Post Processing Fog FX.

**Ambient And Reflections.**

- [ ] Environment Ambient Control.

---------------------------------------------------------------------

## Time Of Day

**DateTime:**

- [ ] Gregorian Calendar Support.
- [ ] System Synchronization.
- [ ] Speed Control.

**Celestial Positions:**

- [ ] Coordinates Based on DateTime.
- [ ] Sun And Moon Position Calculations.

---------------------------------------------------------------------
